/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.projeto.view;

import br.com.projeto.dao.FuncionarioDAO;
import br.com.projeto.model.Funcionarios;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fabricio Vieira
 */
public class FormFuncionario extends javax.swing.JFrame {
    
    
    
    //############## metodo listar funcionários #############
    
    public void lista(){
    
    FuncionarioDAO dao = new FuncionarioDAO();  
    List<Funcionarios> listarFunc = dao.listarFuncionarios();
    DefaultTableModel dados = (DefaultTableModel)listafuncionario.getModel();
    dados.setNumRows(0);
    
        for (Funcionarios funcionarios : listarFunc) {
            dados.addRow(new Object[]{
                funcionarios.getId(),
                funcionarios.getNome(),
                funcionarios.getRg(),
                funcionarios.getCpf(),
                funcionarios.getEmail(),
                funcionarios.getCargo(),
                funcionarios.getAcesso(),
                funcionarios.getTelefone(),
                funcionarios.getCelular(),
                funcionarios.getCep(),
                funcionarios.getEndereco(),
                funcionarios.getNumero(),
                funcionarios.getComplemento(),
                funcionarios.getBairro(),
                funcionarios.getCidade(),
                funcionarios.getEstado()
        });
            
        }
    
    }
    

    

    /**
     * Creates new form FormFuncionario
     */
    public FormFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastroFuncionario = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        codigo = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        rg = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        cpf = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        senha1 = new javax.swing.JLabel();
        cep = new javax.swing.JLabel();
        textrg = new javax.swing.JTextField();
        textcodigo = new javax.swing.JTextField();
        textnome = new javax.swing.JTextField();
        textemail = new javax.swing.JTextField();
        textcpf = new javax.swing.JTextField();
        textcelular = new javax.swing.JTextField();
        textcep = new javax.swing.JTextField();
        cargo = new javax.swing.JLabel();
        textcargo = new javax.swing.JTextField();
        perfil = new javax.swing.JLabel();
        senha2 = new javax.swing.JLabel();
        textnum = new javax.swing.JTextField();
        estado = new javax.swing.JLabel();
        textcidade = new javax.swing.JTextField();
        cidade = new javax.swing.JLabel();
        numero = new javax.swing.JLabel();
        celular = new javax.swing.JLabel();
        texttelefone = new javax.swing.JTextField();
        endereco = new javax.swing.JLabel();
        textendereco = new javax.swing.JTextField();
        btneditar = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        btnenviar = new javax.swing.JButton();
        btnlimpar = new javax.swing.JButton();
        cbnacesso = new javax.swing.JComboBox<>();
        textcomplemento = new javax.swing.JTextField();
        complemento = new javax.swing.JLabel();
        textbairro = new javax.swing.JTextField();
        bairro = new javax.swing.JLabel();
        selectuf = new javax.swing.JComboBox<>();
        textsenha1 = new javax.swing.JPasswordField();
        textsenha2 = new javax.swing.JPasswordField();
        pesquisa = new javax.swing.JTextField();
        btnpesquisa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listafuncionario = new javax.swing.JTable();
        jPanelFuncionario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setDoubleBuffered(false);
        jPanel2.setEnabled(false);

        codigo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        codigo.setText("Código");
        codigo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        nome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nome.setText("Nome");
        nome.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        rg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rg.setText("RG");
        rg.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        email.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        email.setText("E-mail");
        email.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        cpf.setText("CPF");
        cpf.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        telefone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        telefone.setText("Telefone");
        telefone.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        senha1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        senha1.setText("Senha");
        senha1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        cep.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cep.setText("CEP");
        cep.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        textcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcpfActionPerformed(evt);
            }
        });

        cargo.setText("Cargo");
        cargo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        perfil.setText("Perfil");
        perfil.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        senha2.setText("Re. senha");
        senha2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        estado.setText("Estado-UF");
        estado.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        cidade.setText("Cidade");
        cidade.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        numero.setText("N°");
        numero.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        celular.setText("Celular");
        celular.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        texttelefone.setEditable(false);
        texttelefone.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        endereco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        endereco.setText("Endereço");
        endereco.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btneditar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btnexcluir.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnexcluir.setText("Excluir");
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });

        btnenviar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnenviar.setText("Enviar");
        btnenviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnenviarMouseClicked(evt);
            }
        });
        btnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenviarActionPerformed(evt);
            }
        });

        btnlimpar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnlimpar.setText("Limpar");
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });

        cbnacesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Colaborador" }));
        cbnacesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnacessoActionPerformed(evt);
            }
        });

        complemento.setText("Complemento");
        complemento.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        bairro.setText("Bairro");
        bairro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        selectuf.setBackground(new java.awt.Color(204, 204, 204));
        selectuf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectuf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        textsenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textsenha1ActionPerformed(evt);
            }
        });

        textsenha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textsenha2ActionPerformed(evt);
            }
        });

        btnpesquisa.setText("Pesquisa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbnacesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(292, 292, 292))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textcep, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(bairro)
                                                .addGap(18, 18, 18)
                                                .addComponent(textbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(senha2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(selectuf, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(9, 9, 9))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(textemail, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(senha1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(textendereco)
                                                .addGap(27, 27, 27)
                                                .addComponent(numero)
                                                .addGap(18, 18, 18)
                                                .addComponent(textnum, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(34, 34, 34)
                                                .addComponent(btnpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                            .addComponent(textsenha2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textsenha1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textcomplemento, javax.swing.GroupLayout.Alignment.LEADING))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnenviar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnlimpar))
                                .addGap(233, 233, 233))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(cidade))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(textnome, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(email)
                                            .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textrg, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(textcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(72, 72, 72)
                                                .addComponent(textcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(telefone)
                                    .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textcelular, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(texttelefone))
                                .addGap(18, 18, 18)
                                .addComponent(btnexcluir)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(codigo)
                        .addComponent(textcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cargo)
                        .addComponent(textcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbnacesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(perfil))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nome)
                            .addComponent(textnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rg)
                            .addComponent(cpf)
                            .addComponent(textcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email)
                            .addComponent(textemail)
                            .addComponent(senha1)
                            .addComponent(textsenha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cep)
                            .addComponent(textcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bairro)
                            .addComponent(textbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(senha2)
                                    .addComponent(textsenha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(texttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telefone))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(celular)))
                            .addComponent(btnexcluir, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnlimpar)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cidade)
                            .addComponent(estado)
                            .addComponent(selectuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(complemento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(endereco)
                            .addComponent(textendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numero)
                            .addComponent(textnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btneditar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnpesquisa)
                            .addComponent(btnenviar))))
                .addGap(46, 46, 46))
        );

        cadastroFuncionario.addTab("Cadastro de Funcionarios", jPanel2);

        listafuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "RG", "CPF", "EMAIL", "CARGO", "ACESSO", "TELL", "CELULAR", "CEP", "ENDEREÇO", "NUMERO", "COMPLEMENTO", "BAIRRO", "CIDADE", "ESTADO"
            }
        ));
        listafuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listafuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listafuncionario);

        cadastroFuncionario.addTab("Lista de Funcionario", jScrollPane1);

        jPanelFuncionario.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Funcionarios");

        javax.swing.GroupLayout jPanelFuncionarioLayout = new javax.swing.GroupLayout(jPanelFuncionario);
        jPanelFuncionario.setLayout(jPanelFuncionarioLayout);
        jPanelFuncionarioLayout.setHorizontalGroup(
            jPanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFuncionarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        jPanelFuncionarioLayout.setVerticalGroup(
            jPanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncionarioLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroFuncionario))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cadastroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // ############### Chama o lista de funcionarios ####
                          lista();
        
    }//GEN-LAST:event_formWindowActivated

    private void cbnacessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnacessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbnacessoActionPerformed

    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlimparActionPerformed

    private void btnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnenviarActionPerformed

    private void btnenviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnenviarMouseClicked

        Funcionarios obj = new Funcionarios();
        obj.setNome(textnome.getText());
        obj.setRg(textrg.getText());
        obj.setCpf(textcpf.getText());
        obj.setEmail(textemail.getText());
        obj.setSenha(textsenha1.getText());
        obj.setCargo(textcargo.getText());
        obj.setAcesso(cbnacesso.getSelectedItem().toString());
        obj.setTelefone(texttelefone.getText());
        obj.setCelular(textcelular.getText());
        obj.setCep(textcep.getText());
        obj.setEndereco(textendereco.getText());
        obj.setNumero(Integer.parseInt(textnum.getText()));
        obj.setComplemento(textcomplemento.getText());
        obj.setBairro(textbairro.getText());
        obj.setCidade(textcidade.getText());
        obj.setEstado(selectuf.getSelectedItem().toString());

        FuncionarioDAO dao = new FuncionarioDAO();
        dao.cadastrarFuncionario(obj);

    }//GEN-LAST:event_btnenviarMouseClicked

    private void textcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcpfActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // BOTÃO EDITAR
        
        Funcionarios obj = new Funcionarios();
        
        obj.setNome(textnome.getText());
        obj.setRg(textrg.getText());
        obj.setCpf(textcpf.getText());
        obj.setEmail(textemail.getText());
        obj.setSenha(textsenha1.getText());
        obj.setCargo(textcargo.getText());
        obj.setAcesso(cbnacesso.getSelectedItem().toString());
        obj.setTelefone(texttelefone.getText());
        obj.setCelular(textcelular.getText());
        obj.setCep(textcep.getText());
        obj.setEndereco(textendereco.getText());
        obj.setNumero(Integer.parseInt(textnum.getText()));
        obj.setComplemento(textcomplemento.getText());
        obj.setBairro(textbairro.getText());
        obj.setCidade(textcidade.getText());
        obj.setEstado(selectuf.getSelectedItem().toString());
   
        obj.setId(Integer.parseInt(textcodigo.getText()));
        
        FuncionarioDAO dao = new FuncionarioDAO();
        dao.editaFuncionario(obj);
    }//GEN-LAST:event_btneditarActionPerformed

    private void listafuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listafuncionarioMouseClicked
        // Evento de clique que joga os dados da tabela na pagina inicial
        //para edição
        cadastroFuncionario.setSelectedIndex(0);
        textcodigo.setText(listafuncionario.getValueAt(listafuncionario.getSelectedRow(),0).toString());
        textnome.setText(listafuncionario.getValueAt(listafuncionario.getSelectedRow(),1).toString());
        textrg.setText(listafuncionario.getValueAt(listafuncionario.getSelectedRow(),2).toString());
        textcpf.setText(listafuncionario.getValueAt(listafuncionario.getSelectedRow(),3).toString());
        textemail.setText(listafuncionario.getValueAt(listafuncionario.getSelectedRow(),4).toString());
        textsenha1.setText(listafuncionario.getValueAt(listafuncionario.getSelectedRow(),5).toString());
        textcargo.setText(listafuncionario.getValueAt(listafuncionario.getSelectedRow(),6).toString());
        cbnacesso.setSelectedItem(listafuncionario.getValueAt(listafuncionario.getSelectedRow(),7).toString());
        texttelefone.setText(listafuncionario.getValueAt(listafuncionario.getSelectedRow(),8).toString());
        textcelular.setText(listafuncionario.getValueAt(listafuncionario.getSelectedRow(),9).toString());
        textcep.setText(listafuncionario.getValueAt(listafuncionario.getSelectedRow(),10).toString());
        textendereco.setText(listafuncionario.getValueAt(listafuncionario.getSelectedRow(),11).toString());
        textnum.setText(listafuncionario.getValueAt(listafuncionario.getSelectedRow(),12).toString());
        textcomplemento.setText(listafuncionario.getValueAt(listafuncionario.getSelectedRow(),13).toString());
        textbairro.setText(listafuncionario.getValueAt(listafuncionario.getSelectedRow(),14).toString());
        textcidade.setText(listafuncionario.getValueAt(listafuncionario.getSelectedRow(),15).toString());
        selectuf.setSelectedItem(listafuncionario.getValueAt(listafuncionario.getSelectedRow(),16).toString());
        
    }//GEN-LAST:event_listafuncionarioMouseClicked

    private void textsenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textsenha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textsenha1ActionPerformed

    private void textsenha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textsenha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textsenha2ActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
        // metodo excluir
        
        Funcionarios obj = new Funcionarios();
        obj.setId(Integer.parseInt(textcodigo.getText()));
        
        FuncionarioDAO dao = new FuncionarioDAO();
        dao.excluirFuncionario(obj);
    }//GEN-LAST:event_btnexcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bairro;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btnenviar;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btnlimpar;
    private javax.swing.JButton btnpesquisa;
    private javax.swing.JTabbedPane cadastroFuncionario;
    private javax.swing.JLabel cargo;
    private javax.swing.JComboBox<String> cbnacesso;
    private javax.swing.JLabel celular;
    private javax.swing.JLabel cep;
    private javax.swing.JLabel cidade;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel complemento;
    private javax.swing.JLabel cpf;
    private javax.swing.JLabel email;
    private javax.swing.JLabel endereco;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelFuncionario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listafuncionario;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel numero;
    private javax.swing.JLabel perfil;
    private javax.swing.JTextField pesquisa;
    private javax.swing.JLabel rg;
    private javax.swing.JComboBox<String> selectuf;
    private javax.swing.JLabel senha1;
    private javax.swing.JLabel senha2;
    private javax.swing.JLabel telefone;
    private javax.swing.JTextField textbairro;
    private javax.swing.JTextField textcargo;
    private javax.swing.JTextField textcelular;
    private javax.swing.JTextField textcep;
    private javax.swing.JTextField textcidade;
    private javax.swing.JTextField textcodigo;
    private javax.swing.JTextField textcomplemento;
    private javax.swing.JTextField textcpf;
    private javax.swing.JTextField textemail;
    private javax.swing.JTextField textendereco;
    private javax.swing.JTextField textnome;
    private javax.swing.JTextField textnum;
    private javax.swing.JTextField textrg;
    private javax.swing.JPasswordField textsenha1;
    private javax.swing.JPasswordField textsenha2;
    private javax.swing.JTextField texttelefone;
    // End of variables declaration//GEN-END:variables
}
