package br.com.projeto.view;

import br.com.projeto.dao.ClienteDAO;
import br.com.projeto.model.Clientes;
import br.com.projeto.model.Util;
import java.awt.event.KeyEvent;

import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fabricio Vieira
 */
public class FormCliente extends javax.swing.JFrame {

    //Esse metodo Listar Foi criado a mão
    public void listarTabela() {
        ClienteDAO dao = new ClienteDAO();
        List<Clientes> lista = dao.listarCliente();
        DefaultTableModel dados = (DefaultTableModel) tabelaClientes.getModel(); //importa do java swing
        dados.setNumRows(0); //primeiro da um setNumRows para limpar a tabela

        for (Clientes listaRecebeDa : lista) {
            dados.addRow(new Object[]{
                listaRecebeDa.getId(),
                listaRecebeDa.getNome(),
                listaRecebeDa.getRg(),
                listaRecebeDa.getCpf(),
                listaRecebeDa.getEmail(),
                listaRecebeDa.getTelefone(),
                listaRecebeDa.getCelular(),
                listaRecebeDa.getCep(),
                listaRecebeDa.getEndereco(),
                listaRecebeDa.getNumero(),
                listaRecebeDa.getComplemento(),
                listaRecebeDa.getBairro(),
                listaRecebeDa.getCidade(),
                listaRecebeDa.getEstado(), // Esse metodo será chamado lá na linha  580 ou depois
            // private void formWindowActivated(java.awt.event.WindowEvent evt)
            //para ser exibido na tela de Consulta Clientes
            });

        }

    }

    /**
     * Creates new form FormCliente
     */
    public FormCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelGeral1 = new javax.swing.JTabbedPane();
        painelDadosPessoais = new javax.swing.JPanel();
        codigo = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        cep = new javax.swing.JLabel();
        bairro = new javax.swing.JLabel();
        rg = new javax.swing.JLabel();
        textcodigo = new javax.swing.JTextField();
        textnome = new javax.swing.JTextField();
        btnpesquisar = new javax.swing.JButton();
        textemail = new javax.swing.JTextField();
        textbairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textcidade = new javax.swing.JTextField();
        complemento = new javax.swing.JLabel();
        textcomplemento = new javax.swing.JTextField();
        uf = new javax.swing.JLabel();
        selectuf = new javax.swing.JComboBox<>();
        textcep = new javax.swing.JFormattedTextField();
        celular = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        textcelular = new javax.swing.JFormattedTextField();
        texttelefone = new javax.swing.JFormattedTextField();
        textrg = new javax.swing.JFormattedTextField();
        textcpf = new javax.swing.JFormattedTextField();
        cpf = new javax.swing.JLabel();
        textendereco = new javax.swing.JTextField();
        numero = new javax.swing.JLabel();
        textnumero = new javax.swing.JTextField();
        endereco = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        consultanome = new javax.swing.JLabel();
        textconsulta = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        fundoazul = new javax.swing.JPanel();
        titulocadastrodecliente = new javax.swing.JLabel();
        btnnovo = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        painelDadosPessoais.setBackground(new java.awt.Color(255, 255, 255));

        codigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        codigo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        codigo.setText("Código:");

        nome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nome.setText("Nome:");

        email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        email.setText("E-mail:");

        cep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cep.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cep.setText("CEP:");

        bairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bairro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bairro.setText("Bairro:");

        rg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rg.setText("RG:");

        textnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnomeActionPerformed(evt);
            }
        });

        btnpesquisar.setBackground(new java.awt.Color(204, 204, 204));
        btnpesquisar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnpesquisar.setText("Pesquisar");
        btnpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesquisarActionPerformed(evt);
            }
        });

        textemail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        textbairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Cidade:");

        textcidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcidadeActionPerformed(evt);
            }
        });

        complemento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        complemento.setText("Complemento:");

        textcomplemento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        uf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        uf.setText("UF:");

        selectuf.setBackground(new java.awt.Color(204, 204, 204));
        selectuf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectuf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        try {
            textcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textcep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textcep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textcepKeyPressed(evt);
            }
        });

        celular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        celular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        celular.setText("Celular:");

        telefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telefone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        telefone.setText("Telefone:");

        try {
            textcelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textcelular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        try {
            texttelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        texttelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        try {
            textrg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textrg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        try {
            textcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textcpf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cpf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cpf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cpf.setText("CPF");

        textendereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        numero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numero.setText("N°:");

        textnumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        endereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        endereco.setText("Endereço:");

        javax.swing.GroupLayout painelDadosPessoaisLayout = new javax.swing.GroupLayout(painelDadosPessoais);
        painelDadosPessoais.setLayout(painelDadosPessoaisLayout);
        painelDadosPessoaisLayout.setHorizontalGroup(
            painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textnome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                                    .addComponent(textemail)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelDadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(textbairro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)))
                                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnpesquisar)
                                        .addGap(107, 107, 107)
                                        .addComponent(numero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                        .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelDadosPessoaisLayout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addComponent(textcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(complemento)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textcomplemento))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelDadosPessoaisLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(texttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(uf)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(selectuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(textcep, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textrg, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        painelDadosPessoaisLayout.setVerticalGroup(
            painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome)
                    .addComponent(textnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email)
                    .addComponent(celular)
                    .addComponent(textcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cep)
                    .addComponent(textcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero)
                    .addComponent(textnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bairro)
                    .addComponent(textbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(textcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(complemento)
                    .addComponent(textcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uf)
                    .addComponent(selectuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rg)
                    .addComponent(textrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpf))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        painelGeral1.addTab("Dados Pessoais", painelDadosPessoais);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        consultanome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        consultanome.setText("Nome:");

        textconsulta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textconsultaActionPerformed(evt);
            }
        });

        btnPesquisar.setBackground(new java.awt.Color(204, 204, 204));
        btnPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        tabelaClientes.setBackground(new java.awt.Color(204, 204, 204));
        tabelaClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "RG", "CPF", "E-mail", "Telefone", "Celular", "Cep", "Endereço", "Numero", "Comple", "Bairro", "Cidade", "UF"
            }
        ));
        tabelaClientes.setGridColor(new java.awt.Color(204, 204, 204));
        tabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaClientes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(consultanome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisar)
                        .addGap(0, 458, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultanome)
                    .addComponent(textconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painelGeral1.addTab("Consulta de Clientes", jPanel3);

        fundoazul.setBackground(new java.awt.Color(0, 0, 137));

        titulocadastrodecliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titulocadastrodecliente.setForeground(new java.awt.Color(255, 255, 255));
        titulocadastrodecliente.setText("Cadastro de Clientes");

        javax.swing.GroupLayout fundoazulLayout = new javax.swing.GroupLayout(fundoazul);
        fundoazul.setLayout(fundoazulLayout);
        fundoazulLayout.setHorizontalGroup(
            fundoazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoazulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulocadastrodecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fundoazulLayout.setVerticalGroup(
            fundoazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoazulLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(titulocadastrodecliente)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        btnnovo.setBackground(new java.awt.Color(204, 204, 204));
        btnnovo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnnovo.setText("Limpar");
        btnnovo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovoActionPerformed(evt);
            }
        });

        btnsalvar.setBackground(new java.awt.Color(204, 204, 204));
        btnsalvar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnsalvar.setText("Salvar");
        btnsalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        btneditar.setBackground(new java.awt.Color(204, 204, 204));
        btneditar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btneditar.setText("Editar");
        btneditar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btnexcluir.setBackground(new java.awt.Color(204, 204, 204));
        btnexcluir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnexcluir.setText("Excluir");
        btnexcluir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(btnnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(painelGeral1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fundoazul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(fundoazul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelGeral1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnovo, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(btnsalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(btneditar, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(btnexcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcidadeActionPerformed

    private void textnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnomeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_textnomeActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // METODO pesquisar
        String recebeNome = "%" + textconsulta.getText() + "%";

        ClienteDAO dao = new ClienteDAO();
        List<Clientes> novalista = dao.buscaClientePorNome(recebeNome);

        DefaultTableModel dados = (DefaultTableModel) tabelaClientes.getModel();
        dados.setNumRows(0); //primeiro da um setNumRows para limpar a tabela

        for (Clientes listaRecebeDa : novalista) {
            dados.addRow(new Object[]{
                listaRecebeDa.getId(),
                listaRecebeDa.getNome(),
                listaRecebeDa.getRg(),
                listaRecebeDa.getCpf(),
                listaRecebeDa.getEmail(),
                listaRecebeDa.getTelefone(),
                listaRecebeDa.getCelular(),
                listaRecebeDa.getCep(),
                listaRecebeDa.getEndereco(),
                listaRecebeDa.getNumero(),
                listaRecebeDa.getComplemento(),
                listaRecebeDa.getBairro(),
                listaRecebeDa.getCidade(),
                listaRecebeDa.getEstado(), // Esse metodo será chamado lá na linha  580 ou depois
            // private void formWindowActivated(java.awt.event.WindowEvent evt)
            //para ser exibido na tela de Consulta Clientes
            });

        }

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // Botão salvar

        // metodo set lá da minha classe cliente vai englobar para receber e 
        // cadastrar no banco , pegar tudo do get
        // e armazenar no text. (set vai inserir) (text vai receber) (o que tem dentro do get)
        Clientes obj = new Clientes();
        obj.setNome(textnome.getText());
        obj.setRg(textrg.getText());
        obj.setCpf(textcpf.getText());
        obj.setEmail(textemail.getText());
        obj.setTelefone(texttelefone.getText());
        obj.setCelular(textcelular.getText());
        obj.setCep(textcep.getText());
        obj.setEndereco(textendereco.getText());
        obj.setNumero(Integer.parseInt(textnumero.getText()));
        obj.setComplemento(textcomplemento.getText());
        obj.setBairro(textbairro.getText());
        obj.setCidade(textcidade.getText());
        obj.setEstado(selectuf.getSelectedItem().toString());

        ClienteDAO dao = new ClienteDAO();
        dao.cadastrarCliente(obj); // VAI CADASTRAR os dados utilizando o metodo feito no ClienteDAO

        //Metodo de limpar tem uma pegadinha
        //ele limpa o painel principal. todos os elementos faz edição pela principal.
        new Util().LimparTela(painelDadosPessoais);


    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btnnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovoActionPerformed
        // TODO add your handling code here:

        //Metodo de limpar tem uma pegadinha
        //ele limpa o painel principal. todos os elementos faz edição pela principal.
        new Util().LimparTela(painelDadosPessoais);
    }//GEN-LAST:event_btnnovoActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
        // Deletar do banco de dados.
        Clientes obj = new Clientes();
        obj.setId(Integer.parseInt(textcodigo.getText()));

        ClienteDAO dao = new ClienteDAO();
        dao.excluirCliente(obj);

        //Metodo de limpar tem uma pegadinha
        //ele limpa o painel principal. todos os elementos faz edição pela principal.
        painelGeral1.setSelectedIndex(1);


    }//GEN-LAST:event_btnexcluirActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Chamar o metodo criado
        listarTabela();
    }//GEN-LAST:event_formWindowActivated

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // Metodo Editar

        Clientes obj = new Clientes();
        obj.setNome(textnome.getText());
        obj.setRg(textrg.getText());
        obj.setCpf(textcpf.getText());
        obj.setEmail(textemail.getText());
        obj.setTelefone(texttelefone.getText());
        obj.setCelular(textcelular.getText());
        obj.setCep(textcep.getText());
        obj.setEndereco(textendereco.getText());
        obj.setNumero(Integer.parseInt(textnumero.getText()));
        obj.setComplemento(textcomplemento.getText());
        obj.setBairro(textbairro.getText());
        obj.setCidade(textcidade.getText());
        obj.setEstado(selectuf.getSelectedItem().toString());
        //campo ID que ficou faltando para funcionar o editar
        obj.setId(Integer.parseInt(textcodigo.getText()));

        ClienteDAO dao = new ClienteDAO();
        dao.alterarCliente(obj); //Vai alterar os clientes no banco, pega as
        //informações do DAO e aplica no banco de dados

        //Metodo de limpar tem uma pegadinha
        //ele limpa o painel principal. todos os elementos faz edição pela principal.
        new Util().LimparTela(painelDadosPessoais);

    }//GEN-LAST:event_btneditarActionPerformed

    private void tabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClientesMouseClicked
        // primeiro fazer com que ele mude para a aba e o index desejado
        //se colocar 0 ele vai para a primeira aba que é o dados Pessoais
        painelGeral1.setSelectedIndex(0);

        //agora para pegar o que foi selecionado através do click, fará isso para 
        //todos os campos da tabela, GetSelectedRow é uma function que seleciona o que foi clicado
        //ToString para transformar em uma String.
        //tabelaClientes é a tabela de exibição de todos os clientes em consulta clientes
        textcodigo.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 0).toString());
        textnome.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 1).toString());
        textrg.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 2).toString());
        textcpf.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 3).toString());
        textemail.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 4).toString());
        texttelefone.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 5).toString());
        textcelular.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 6).toString());
        textcep.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 7).toString());
        textendereco.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 8).toString());
        textnumero.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 9).toString());
        textcomplemento.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 10).toString());
        textbairro.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 11).toString());
        textcidade.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 12).toString());
        selectuf.setSelectedItem(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 0).toString());

    }//GEN-LAST:event_tabelaClientesMouseClicked

    private void textconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textconsultaActionPerformed
        // METODO CONSULTAR NOME.


    }//GEN-LAST:event_textconsultaActionPerformed

    private void btnpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisarActionPerformed
        // Metodo Pesquisar
      
            String pesquisa = textnome.getText(); //pega o valor digitado no textnome  
            Clientes obj = new Clientes();
            ClienteDAO dao = new ClienteDAO();
            obj = dao.pesquisaDeUmCliente(pesquisa);

            //Exibir os dados do obj nos campos de Texto
            if(obj!= null){
            textcodigo.setText(String.valueOf(obj.getId()));
            textnome.setText(obj.getNome());
            textrg.setText(obj.getRg());
            textcpf.setText(obj.getCpf());
            textemail.setText(obj.getEmail());
            texttelefone.setText(obj.getTelefone());
            textcelular.setText(obj.getCelular());
            textcep.setText(obj.getCep());
            textendereco.setText(obj.getEndereco());
            textnumero.setText(String.valueOf(obj.getNumero()));
            textcomplemento.setText(obj.getComplemento());
            textbairro.setText(obj.getBairro());
            textcidade.setText(obj.getCidade());
            selectuf.setSelectedItem(obj.getEstado());
            }
            else
               JOptionPane.showMessageDialog(null,"Usuário não encontrado!");
            
    }//GEN-LAST:event_btnpesquisarActionPerformed

    private void textcepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textcepKeyPressed
        //Programacao do keypress
	if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
         Clientes obj =  new Clientes();
         ClienteDAO dao = new ClienteDAO();
         obj = dao.buscaCep(textcep.getText());
         
         textendereco.setText(obj.getEndereco());
         textbairro.setText(obj.getBairro());
         textcidade.setText(obj.getCidade());
         selectuf.setSelectedItem(obj.getEstado());               
         
         
     }
    }//GEN-LAST:event_textcepKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bairro;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btnnovo;
    private javax.swing.JButton btnpesquisar;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JLabel celular;
    private javax.swing.JLabel cep;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel complemento;
    private javax.swing.JLabel consultanome;
    private javax.swing.JLabel cpf;
    private javax.swing.JLabel email;
    private javax.swing.JLabel endereco;
    private javax.swing.JPanel fundoazul;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel numero;
    private javax.swing.JPanel painelDadosPessoais;
    private javax.swing.JTabbedPane painelGeral1;
    private javax.swing.JLabel rg;
    private javax.swing.JComboBox<String> selectuf;
    private javax.swing.JTable tabelaClientes;
    private javax.swing.JLabel telefone;
    private javax.swing.JTextField textbairro;
    private javax.swing.JFormattedTextField textcelular;
    private javax.swing.JFormattedTextField textcep;
    private javax.swing.JTextField textcidade;
    private javax.swing.JTextField textcodigo;
    private javax.swing.JTextField textcomplemento;
    private javax.swing.JTextField textconsulta;
    private javax.swing.JFormattedTextField textcpf;
    private javax.swing.JTextField textemail;
    private javax.swing.JTextField textendereco;
    private javax.swing.JTextField textnome;
    private javax.swing.JTextField textnumero;
    private javax.swing.JFormattedTextField textrg;
    private javax.swing.JFormattedTextField texttelefone;
    private javax.swing.JLabel titulocadastrodecliente;
    private javax.swing.JLabel uf;
    // End of variables declaration//GEN-END:variables
}
